#pragma once
#include "../../global/types.h"

#define LAST_FURR_FLIPEFFECT 512
#define FIRST_FURR_FLIPEFFECT 47

#define MAX_FURR_COMMANDS 4096

extern int8_t furr_oneshot_buffer[LAST_FURR_FLIPEFFECT];

enum FURROpcode {
	FURR_ONESHOT = 0,
	FURR_EQUIP,
	FURR_HOLSTER_WEAPONS,
	FURR_INC_HP,
	FURR_DEC_HP,
	FURR_INC_AIR,
	FURR_DEC_AIR,
	FURR_INC_SPRINT,
	FURR_DEC_SPRINT,
	FURR_SET_POISON,
	FURR_KILL_LARA,
	FURR_REMOVE_PISTOLS,
	FURR_SET_BINOCULARS,
	FURR_SET_CROWBAR,
	FURR_SET_LASERSIGHT,
	FURR_DEACTIVATE_WEAPONS,
	FURR_ACTIVATE_PISTOLS,
	FURR_ACTIVATE_UZIS,
	FURR_ACTIVATE_REVOLVER,
	FURR_ACTIVATE_SHOTGUN,
	FURR_ACTIVATE_GRENADEGUN,
	FURR_ACTIVATE_CROSSBOW,
	FURR_EMPTY_HOLSTERS,
	FURR_FILL_HOLSTERS,
	FURR_EMPTY_BACKDRAW,
	FURR_FILL_BACKDRAW,
	FURR_REMOVE_ALL_GUNS,
	FURR_CALL_FLIP,
	FURR_MOV_BYTE,
	FURR_MOV_WORD,
	FURR_MOV_DWORD,
	FURR_ADD_KEY,
	FURR_REMOVE_KEY,
	FURR_ADD_QUESTITEM,
	FURR_REMOVE_QUESTITEM,
	FURR_ADD_EXAMINE1,
	FURR_REMOVE_EXAMINE1,
	FURR_ADD_EXAMINE2,
	FURR_REMOVE_EXAMINE2,
	FURR_ADD_EXAMINE3,
	FURR_REMOVE_EXAMINE3,
	FURR_SET_WATERSKIN1,
	FURR_SET_WATERSKIN2,
	FURR_SET_PUZZLEITEM,
	FURR_ADD_PUZZLEITEM,
	FURR_ADD_PUZZLECOMBO,
	FURR_SET_SUPPLY,
	FURR_ADD_SUPPLY,
	FURR_ADD_WEAPON,
	FURR_REMOVE_WEAPON,
	FURR_START_TIMER,
	FURR_START_TIMER_FROM,
	FURR_SET_TIMER,
	FURR_STOP_TIMER,
	FURR_FREEZE_NORMAL_TIMER,
	FURR_FREEZE_INVERTED_TIMER,
	FURR_LOAD_LEVEL,
	FURR_FLASH_RED,
	FURR_FLASH_ORANGE,
	FURR_FLASH_YELLOW,
	FURR_FLASH_GREEN,
	FURR_FLASH_LIGHTGREEN,
	FURR_FLASH_BLUE,
	FURR_SHAKE_CAMERA,
	FURR_SHAKE_CAMERA_SOFT,
	FURR_SHAKE_CAMERA_MEDIUM,
	FURR_SHAKE_CAMERA_HEAVY,
	FURR_LARA_DRIPS,
	FURR_SET_LEGEND_TIME,
	FURR_SET_LEGEND_STRING,
	FURR_PLAY_ANIM,
	FURR_ORIENTATE,
	FURR_ROTATE,
	FURR_CHANGE_POSITION_X,
	FURR_CHANGE_POSITION_Y,
	FURR_CHANGE_POSITION_Z,
	FURR_CHANGE_ACCEL,
	FURR_CHANGE_VERT_ACCEL,
	FURR_CHANGE_ROOM,
	FURR_ADD_POSITION,
	FURR_UVROTATE,
	FURR_MOVE_ITEM_X,
	FURR_MOVE_ITEM_Y,
	FURR_MOVE_ITEM_Z,
	FURR_KILL_ITEM,
	FURR_SET_HP,
	FURR_SPEEDDN,
	FURR_SPEEDUP,
	FURR_CAMERA_FOLLOW,
	FURR_LOCK_CONTROLS,
	FURR_UNLOCK_CONTROLS,
	FURR_MOVE_MIRROR,
	FURR_ONESHOT_STATE,
	FURR_SWAP_INVENTORY,
	FURR_CHANGE_WEATHER,
	FURR_SWAP_LARA_MESH,
	FURR_RETURN_TRUE,
	FURR_STOP,
	FURR_RESET,
	FURR_RET,
	FURR_RETN,
	FURR_NOP,
	FURR_USE_BINOCULARS,
	FURR_ADD_DIARY,
	FURR_ACTIVATE_BAR,
	FURR_DEACTIVATE_BAR,
	FURR_CALL,
	FURR_SHATTER_ITEM,
	FURR_LARA_ON_FIRE,
	FURR_BLEED,
	FURR_SHOW_STATS,
	FURR_DRAW_BMP,
	FURR_PLAY_SAMPLE,
	FURR_PLAY_SOUNDTRACK,
	FURR_SAVE_GAME,
	FURR_LOAD_GAME,
	FURR_PICKUP_ITEM,
	FURR_DRAW_ITEM,
	FURR_FADEOUT,
	FURR_SHOW_INVENTORY,
	FURR_PLAY_FMV,
	FURR_ACTIVATE_ITEM,
	FURR_DAMP_LOOPED,
	FURR_ONLY_IN_WATER,
	FURR_ONLY_ON_LAND,
	FURR_ENVIRONMENT,
	FURR_NO_FADEOUT,

	FURR_IF_PRESSED,
	FURR_IF_NOT_PRESSED,

	FURR_IF_LARA_EQUAL, // ==
	FURR_IF_LARA_NOT, // !=
	FURR_IF_LARA_GREATER_THAN, // >
	FURR_IF_LARA_LESS_THAN, // <
	FURR_IF_LARA_EQUAL_OR_GREATER_THAN, // >=
	FURR_IF_LARA_EQUAL_OR_LESS_THAN, // <=

	FURR_IF_CARRY_GUNS,
	FURR_IF_NOT_CARRY_GUNS,

	FURR_BYTE_IF_EQL, // ==
	FURR_BYTE_IF_NOT, // !=
	FURR_BYTE_IF_GT, // >
	FURR_BYTE_IF_LT, // <
	FURR_BYTE_IF_ELT, // >=
	FURR_BYTE_IF_EGT, // <=

	FURR_WORD_IF_EQL, // ==
	FURR_WORD_IF_NOT, // !=
	FURR_WORD_IF_GT, // >
	FURR_WORD_IF_LT, // <
	FURR_WORD_IF_ELT, // >=
	FURR_WORD_IF_EGT, // <=

	FURR_DWORD_IF_EQL, // ==
	FURR_DWORD_IF_NOT, // !=
	FURR_DWORD_IF_GT, // >
	FURR_DWORD_IF_LT, // <
	FURR_DWORD_IF_ELT, // >=
	FURR_DWORD_IF_EGT, // <=

	FURR_OPCODE_COUNT
};

struct FURRNameTableEntry {
	const char *opcode_name;
	const FURROpcode opcode_token;
};

extern FURRNameTableEntry furr_name_table[];

enum FURRResult {
	FURR_RESULT_ERROR = -3,
	FURR_RESULT_UNIMPLEMENTED = -2,
	FURR_RESULT_RET = -1,
	FURR_RESULT_FAILED = 0,
	FURR_RESULT_OK = 1
};

struct FURRParameters {
	FURRResult previous_result;

	int first_parameter = 0;
	int second_parameter = 0;
};

struct FURRDataTable {
	const int arg_count;
	FURRResult (*func_ptr)(FURRParameters);
};

extern FURRDataTable furr_data_table[];

struct FURRFlipeffectTable {
	int size = 0;
	int *tokens = nullptr;
};

extern int furr_get_arg_count_for_opcode(const FURROpcode opcode);
extern int furr_get_opcode_for_command_string(const char* command_name);

extern void furr_clear_oneshot_buffer();
extern void furr_execute_furr_flipeffect(int id);
extern void furr_allocate_flipeffect_buffer(int flipeffect_id, int size);
extern void furr_free_all_flipeffect_buffers();
extern void furr_add_flipeffect_token(int flipeffect_id, int token);
