#pragma once

enum NGProgressiveActionType {
	AZ_NONE, 
	AZ_ROTATE_ITEM_HORIZONTAL,
	AZ_ROTATE_ITEM_VERTICAL,
	AZ_RESET_DISABLED_INPUT,
	AZ_RESET_SIMULATED_INPUT,
	AZ_HIDE_SCREEN,
	AZ_FORCE_VOLUMETRIC_FX,
	AZ_PRINT_STRING,
	AZ_SOUND_SAMPLE,
	AZ_TURN_FACING_HORIZONTAL,
	AZ_TURN_FACING_VERTICAL,
	AZ_DELAY_TRIGGER,
	AZ_ADD_EFFECT,
	AZ_MOVE_ANIMATING,
	AZ_BLINK_MIRROR,
	AZ_LARA_TRANSPARENT,
	AZ_LARA_IMMORTAL,
	AZ_PREPARE_MOVIE,
	AZ_TEXTURE_SEQUENCE,
	AZ_MOVE_ROLLINGBALL,
	AZ_MIST_ROLLINGBALL,
	AZ_TRAP_PUSHABLE,
	AZ_PUSH_PUSHABLE,
	AZ_CAMERA_TARGET,
	AZ_CAMERA_AXIS,
	AZ_CAMERA_EFFECT,
	AZ_CHANGE_LAYER_COLOR,
	AZ_MOVE_ADVANCED,
	AZ_WAIT_KILL,
	AZ_MOVE_STATIC,
	AZ_MOVE_MOVEABLE,
	AZ_ROTATE_STATIC,
	AZ_ROTATE_MOVEABLE,
	AZ_CHANGE_COLOR_STATIC,
	AZ_CHANGE_COLOR_MOVEABLE,
	AZ_TRIGGER_GROUP_CONTINUOUS,
	AZ_SHOW_TIMER_ITEM,
	AZ_PLAY_CD_RESTORE,
	AZ_CHANGE_FOG_DISTANCE,
	AZ_PULSE_FOG_DISTANCE,
	AZ_SCROLLING_VTEXT,
	AZ_SCROLLING_HTEXT,
	AZ_TEMP_FREE_HANDS,
	AZ_SET_CAMERA,
	AZ_SHOW_FLARE_LIGHT,
	AZ_TRANSPARENT_ENEMY,
	AZ_CHANGE_FOG_DENSITY,
	AZ_TIMER_TRNG,
	AZ_SHOW_TIMER_TRNG,
	AZ_RESUME_FROZEN,
	AZ_SHOW_CUSTOM_BAR,
	AZ_ALTERNATE_FLIPMAP,
};

#define NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT 6

struct NGProgressiveAction {
	NGProgressiveActionType type;
	int16_t item_index;
	uint16_t duration;
	union {
		uint16_t argument1_u16;
		uint8_t argument1_u8[2];
	};
	union {
		float argument2_f32[6];

		uint32_t argument2_u32[NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT];
		int32_t  argument2_i32[NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT];
		uint16_t argument2_u16[NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT * 2];
		int16_t argument2_s16[NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT * 2];
		uint8_t argument2_u8[NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT * 4];
		int8_t argument2_s8[NG_PROGRESSIVE_ACTION_ARGUMENT_2_COUNT * 4];
	};
};

#define NG_MAX_PROGRESSIVE_ACTIONS 100

extern NGProgressiveAction progressive_actions[NG_MAX_PROGRESSIVE_ACTIONS];
extern int32_t progressive_action_count;

extern NGProgressiveAction *NGCreateProgressiveAction();
extern void NGExecuteProgressiveActions();