#pragma once
#include "../global/types.h"

void handle_cutseq_triggering(int32_t name);
void do_new_cutscene_camera();
void InitPackNodes(NODELOADHEADER* lnode, PACKNODE* pnode, char* packed, int32_t numnodes);
void DecodeAnim(PACKNODE* node, int32_t num_nodes, int32_t frame, int32_t flags);
int16_t DecodeTrack(char* packed, RTDECODE* decode);
int16_t GetTrackWord(int32_t off, char* packed, int32_t packmethod);
void fix_lara_for_cutseq();
void updateAnimFrame(PACKNODE* node, int32_t flags, int16_t* frame);
void* cutseq_malloc(int32_t size);
void finish_cutseq();
void DrawCutSeqActors();
void CalcActorLighting(ITEM_INFO* item, OBJECT_INFO* obj, int16_t* rot);
void GetJointAbsPositionCutSeq(ITEM_INFO* item, OBJECT_INFO* obj, int16_t* rot, PHD_VECTOR* pos);
void CalculateObjectLightingLaraCutSeq();
void third_cutseq_control();
void fourth_cutseq_init();
void fourth_cutseq_control();
void fourth_cutseq_end();
void fifth_cutseq_control();
void fifth_cutseq_end();
void sixth_cutseq_init();
void sixth_cutseq_control();
void sixth_cutseq_end();
void seventh_cutseq_init();
void seventh_control();
void eighth_control();
void ninth_cutseq_init();
void ninth_control();
void tenth_cutseq_init();
void tenth_cutseq_control();
void tenth_cutseq_end();
void eleventh_cutseq_init();
void eleventh_cutseq_control();
void twelth_cutseq_init();
void twelth_cutseq_end();
void thirteen_end();
void fourteen_end();
void fourteen_control();
void fifteen_init();
void fifteen_control();
void fifteen_end();
void sixteen_init();
void sixteen_control();
void sixteen_end();
void seventeen_control();
void seventeen_end();
void eighteen_init();
void eighteen_control();
void eighteen_end();
void nineteen_init();
void nineteen_control();
void nineteen_end();
void twenty_control();
void twenty_end();
void twentyone_init();
void twentyone_end();
void twentythree_init();
void twentythree_control();
void twentythree_end();
void twentyfour_init();
void twentyfour_control();
void twentyfour_end();
void twentyfive_control();
void twentyfive_end();
void twentyfive_init();
void twentysix_control();
void twentyseven_init();
void twentyseven_control();
void twentyseven_end();
void twentytwo_init();
void twentytwo_end();
void do_spade_meshswap();
void do_key_meshswap();
void cutseq_shoot_pistols(int32_t left_or_right);
void trigger_weapon_dynamics(int32_t left_or_right);
void deal_with_pistols();
void cutseq_kill_item(int32_t num);
ITEM_INFO* cutseq_restore_item(int32_t num);
int32_t Load_and_Init_Cutseq(int32_t num);
void init_cutseq_actors(char* data, int32_t resident);
void init_voncroy_meshbits(int32_t num);
void DelsHandyTeleportLara(int32_t x, int32_t y, int32_t z, int32_t yrot);
void nail_intelligent_object(int16_t num);
void handle_lara_chatting(int16_t* _ranges);
void handle_actor_chatting(int32_t speechslot, int32_t node, int32_t slot, int32_t objslot, int16_t* _ranges);
void trigger_item_in_room(int32_t room_number, int32_t object_number);
void untrigger_item_in_room(int32_t room_number, int32_t object_number);
ITEM_INFO* find_an_item_with_object_type(int32_t object_number);
void special2_end();
void special2_init();
void special3_end();
void special3_control();
void special1_init();
void special1_end();
void times_init();
void times_control();

extern int32_t cutseq_trig;
extern int32_t cutseq_num;
extern int32_t GLOBAL_playing_cutseq;
extern int32_t GLOBAL_cutseq_frame;
