#pragma once
#include "../../../global/types.h"

void InitialiseGuide(int16_t item_number);
void GuideControl(int16_t item_number);

#define GUIDE_STATE_EMPTY 0
#define GUIDE_STATE_STOP 1
#define GUIDE_STATE_WALK 2
#define GUIDE_STATE_RUN 3
#define GUIDE_STATE_CHECK_GROUND 7
#define GUIDE_STATE_USE_LIGHTER 11
#define GUIDE_STATE_TURN_LEFT 22
#define GUIDE_STATE_ATTACK_LOW 31
#define GUIDE_STATE_TURN_RIGHT 35
#define GUIDE_STATE_CROUCH 36
#define GUIDE_STATE_GRAB_TORCH 37
#define GUIDE_STATE_READ_INSCRIPTION_SHORT 38
#define GUIDE_STATE_READ_INSCRIPTION_SLOW_SCARY 39
#define GUIDE_STATE_STAND_TO_WALK 40
#define GUIDE_STATE_CORRECT_POSITION_FRONT 41
#define GUIDE_STATE_CORRECT_POSITION_BACK 42
#define GUIDE_STATE_CROUCH_TORCH_ACTIVATE 43

#define GUIDE_STAND_ANIMATION 4
#define GUIDE_STAND_TO_CROUCH_ANIMATION 57
#define GUIDE_READ_INSCRIPTION_ANIMATION 61