#pragma once
#include "../../../global/types.h"

void TriggerRiseEffect(ITEM_INFO* item);
void InitialiseSkeleton(int16_t item_number);
void SkeletonControl(int16_t item_number);

#define SKELETON_STATE_UNDERGROUND 0
#define SKELETON_STATE_WAIT 1
#define SKELETON_STATE_IDLE 2
#define SKELETON_STATE_LOOK_LEFT 3
#define SKELETON_STATE_LOOK_RIGHT 4
#define SKELETON_STATE_DODGE_LEFT 5
#define SKELETON_STATE_DODGE_RIGHT 6
#define SKELETON_STATE_USE_SHIELD 7
#define SKELETON_STATE_ATTACK_1 8
#define SKELETON_STATE_ATTACK_2 9
#define SKELETON_STATE_ATTACK_3 10
#define SKELETON_STATE_STUCK_SWORD 11
#define SKELETON_STATE_RECOIL_FRONT 12
#define SKELETON_STATE_RECOIL_BACK 13
#define SKELETON_STATE_STAND_UP 14
#define SKELETON_STATE_WALK_FORWARD 15
#define SKELETON_STATE_RUN_FORWARD 16
#define SKELETON_STATE_BLOCK_ATTACK 17
#define SKELETON_STATE_WALK_ATTACK 18
#define SKELETON_STATE_JUMP_LEFT 19
#define SKELETON_STATE_JUMP_RIGHT 20
#define SKELETON_STATE_JUMP_FORWARD_1_BLOCK 21
#define SKELETON_STATE_JUMP_FORWARD_2_BLOCKS 22
#define SKELETON_STATE_JUMP_CONTINUE 23
#define SKELETON_STATE_JUMP_START 24
#define SKELETON_STATE_LAYING_DOWN 25